### ISSUE TITLE
【官方解答】模块管理、主题管理、插件管理  报错404

### ISSUE THREAD

**Issue by Hackxiaoya** [Hackxiaoya/CuteOne#27]
模块文件夹路径：app\model\
请确保目录下只有README.md文件和别的模块文件夹，否则是会报错404的；  

插件文件夹路径：app\plugin\
请确保目录下只有README.md文件和别的插件文件夹，否则是会报错404的；  

主题文件夹路径：app\templates\themes\
请确保目录下只有default文件和别的主题文件夹，否则是会报错404的；

**Comment by momeigui** [comment]
我已经确保了文件夹路径下只有这个文件与插件文件夹，但是仍然会404报错，尝试过重新启动网站，都以失败告终
控制台提示
127.0.0.1 - - [30/Jul/2019 18:47:19] "GET /admin/plugin/onlineUpgrade/admin/examine HTTP/1.0" 404 -

**Comment by momeigui** [comment]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/www/wwwroot/cloud.spem/app/common.py", line 48, in decorator
    return func(*args,**kwargs)
  File "/www/wwwroot/cloud.spem/app/plugin/onlineUpgrade/admin/views.py", line 11, in onlineUpgrade_examine
    result = logic.get_versions()
  File "/www/wwwroot/cloud.spem/app/plugin/onlineUpgrade/logic.py", line 17, in get_versions
    res = requests.post(url, data=payload)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.cuteone.cn', port=80): Max retries exceeded with url: /cuteone/version/index (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb6c6a4c630>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by Hackxiaoya** [comment]
在线更新暂时停用。
