### ISSUE TITLE
个人版不支持？

### ISSUE THREAD

**Issue by WoChen5770** [Hackxiaoya/CuteOne#8]
个人版创建应用程序的时候没有目录，不能指定所有者。导致获取的code无效 code例如M1f56fe0a-d032-32c6-5c78-34d0c494cc33

**Comment by WoChen5770** [comment]
之前用pyone或者oneindex都可以

**Comment by Hackxiaoya** [comment]
如果pyone和oneindex都支持。那么cuteone也是支持的。

**Comment by littlef0x** [comment]
可能是有一些问题，我在同一个页面添加个人版和A1，A1正常，个人版无法更新缓存，并且二者的code格式不同，生成code的url格式也不同。
对比了OLAINDEX和CuteOne的Application页面，除了redirect url外似乎没什么不同，前者一切正常，原因我也不了解。

**Comment by Hackxiaoya** [comment]
你可以群里at我一下。然后截图看看。帮你排查一下。 因为绑定网盘这个位置是百分百没有问题的。如果有，那么就是你自己的账号问题或者操作问题；

**Comment by littlef0x** [comment]
cuteone版本1.x最新版，已经尝试两个个人版账号，均无法刷新缓存，不显示文件，A1一次成功可以正常显示文件。
操作步骤是这样的：登陆Microsoft账号，在CuteOne中添加网盘，获取secret和id，获取code，个人版显示的url是http://127.0.0.1/?code=Mxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx ，A1版的url比较长我没有记录，填入code之后没有报错，之后刷新缓存，刷新按钮会变灰，等待几分钟后恢复蓝色，但是网盘列表中的缓存量显示是0，点管理会404。
我没有找到cuteone的日志，在journalctl中有大量如下信息（已脱敏）：

> Apr 29 xx:xx:xx user uwsgi[584]: During handling of the above exception, another exception occurred:
Apr 29 xx:xx:xx user uwsgi[584]: Traceback (most recent call last):
Apr 29 xx:xx:xx user uwsgi[584]:   File "/www/wwwroot/xxx.xxx.com/CuteOne/app/task/cuteTask.py", line 64, in task_getlist
Apr 29 xx:xx:xx user uwsgi[584]:     "createdDateTime": common.utc_to_local(i["fileSystemInfo"]["createdDateTime"]),
Apr 29 xx:xx:xx user uwsgi[584]:   File "/www/wwwroot/xxx.xxx.com/CuteOne/app/common.py", line 49, in utc_to_local
Apr 29 xx:xx:xx user uwsgi[584]:     utcTime = datetime.datetime.strptime(utc, UTC_FORMAT)
Apr 29 xx:xx:xx user uwsgi[584]:   File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
Apr 29 xx:xx:xx user uwsgi[584]:     tt, fraction = _strptime(data_string, format)
Apr 29 xx:xx:xx user uwsgi[584]:   File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
Apr 29 xx:xx:xx user uwsgi[584]:     (data_string, format))
Apr 29 xx:xx:xx user uwsgi[584]: ValueError: time data '2019-01-29T04:51:19.036Z' does not match format '%Y-%m-%dT%H:%M:%SZ'

似乎日期格式不对，不清楚是否是无法刷新的原因，请查看，谢谢

**Comment by littlef0x** [comment]
补充一下，Onedrive账号是office365家庭版，一个是管理员，一个是成员，都是这样的情况

**Comment by Hackxiaoya** [comment]
@littlef0x 不支持吧。大概，我猜。

**Comment by WoChen5770** [comment]
@littlef0x 我提交了一个pull request，个人版没问题了

**Comment by WoChen5770** [comment]
@littlef0x  也可以https://github.com/WoChen5770/CuteOne.git

**Comment by Hackxiaoya** [comment]
@WoChen5770 时区的问题？

**Comment by WoChen5770** [comment]
@Hackxiaoya 个人版返回的时间带有毫秒

**Comment by Hackxiaoya** [comment]
@WoChen5770 晚点我再测试你推的代码分支；

**Comment by littlef0x** [comment]
测试了@WoChen5770 的分支，缓存可以正常更新，感谢二位！
不过出现了和PyOne一样的问题（这个[issue](https://github.com/abbeyokgo/PyOne/issues/67)），即如果目录名包含某些字符（可能包括空格、中文括号、点等），那么该目录下层级数大于某个数时，文件会不显示，具体我也没有找到什么规律，有点怀疑是API的问题了╮（╯＿╰）╭

**Comment by littlef0x** [comment]
翻了下issue，可能跟[这个](https://github.com/Hackxiaoya/CuteOne/issues/18)是一回事。
我年初的时候测试OLAINDEX是正常的，或许可以参考一下他的实现

**Comment by Hackxiaoya** [comment]
@littlef0x 编码问题

**Comment by littlef0x** [comment]
> 
> 
> @littlef0x 编码问题

可以在cuteone端修复么？
